### ISSUE TITLE
Failed to instantiate component or class "bymayo\porter\variables\PorterVariable"

### ISSUE THREAD

**Issue by flo-bananzki** [bymayo/craft-porter#2]
Hi Jason, there is a problem to include the DeleteAccountForm into my Templates (see Stack trace).
Loading the Form with `{{ craft.porter.deleteAccountForm() }}`

on this line:
https://github.com/bymayo/craft-porter/blob/44ce2878f4f8d58c60a8c1d4bcd2dc92590bcdd0/src/templates/components/deleteAccountForm.twig#L1

I then scrolled through the History of the Plugin and saw, that you removed the namespace an the inherited libaries in the defective file: `/src/variables/PorterVariable.php` few Months ago.
So I just added them again and it works now ✌.

added to file `/src/variables/PorterVariable.php`:
```
namespace bymayo\porter\variables;
use bymayo\porter\Porter;
use Craft;
```

**System:**
Craft CMS 4.2.1.1
PHP version 8.1.9
Linux 5.4.0-72-generic
MySQL 8.0.23

**Here the Errors:**

**Not instantiable – [yii\di\NotInstantiableException](http://www.yiiframework.com/doc-2.0/yii-di-notinstantiableexception.html)**
**Failed to instantiate component or class "bymayo\porter\variables\PorterVariable".**

**ReflectionException: Class "bymayo\porter\variables\PorterVariable" does not exist in /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php:507**

<details> 
  <summary>Stack trace:</summary>

```
#0 /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#1 /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#2 /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#3 /home/vagrant/xx/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get()
#4 /home/vagrant/xx/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()
#5 /home/vagrant/xx/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\di\ServiceLocator->get()
#6 /home/vagrant/xx/vendor/craftcms/cms/src/helpers/Template.php(90): yii\di\ServiceLocator->__get()
#7 /home/vagrant/xx/storage/runtime/compiled_templates/e1/e1e944121636c2b1847dfdf004b49ece.php(41): craft\helpers\Template::attribute()
#8 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d3e78d63bf730e1f32521fa5c08aa48d->doDisplay()
#9 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#10 /home/vagrant/xx/storage/runtime/compiled_templates/08/082642088bfadabf7d3776435bb0e552.php(292): Twig\Template->display()
#11 /home/vagrant/xx/vendor/twig/twig/src/Template.php(171): __TwigTemplate_7129d93ddf3d1787758882ea8da39810->block_account()
#12 /home/vagrant/xx/storage/runtime/compiled_templates/b7/b7ce87a899d73972bedb70bcb29e1e8e.php(75): Twig\Template->displayBlock()
#13 /home/vagrant/xx/vendor/twig/twig/src/Template.php(171): __TwigTemplate_45fbd9b2468fd874474b0351c09ece51->block_content()
#14 /home/vagrant/xx/storage/runtime/compiled_templates/32/32a8ae1bc72d719289deb9e15af6ef11.php(166): Twig\Template->displayBlock()
#15 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_39c7f8fc1f11d4ab3a2f68b3e1f41840->doDisplay()
#16 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#17 /home/vagrant/xx/storage/runtime/compiled_templates/b7/b7ce87a899d73972bedb70bcb29e1e8e.php(49): Twig\Template->display()
#18 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_45fbd9b2468fd874474b0351c09ece51->doDisplay()
#19 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#20 /home/vagrant/xx/storage/runtime/compiled_templates/08/082642088bfadabf7d3776435bb0e552.php(49): Twig\Template->display()
#21 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7129d93ddf3d1787758882ea8da39810->doDisplay()
#22 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#23 /home/vagrant/xx/storage/runtime/compiled_templates/d1/d1ab8f71c923eafdf8501b95da04e4d3.php(55): Twig\Template->display()
#24 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4cf20a0adc7635f753889fec41c95f6e->doDisplay()
#25 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#26 /home/vagrant/xx/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#27 /home/vagrant/xx/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#28 /home/vagrant/xx/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#29 /home/vagrant/xx/vendor/craftcms/cms/src/web/View.php(428): Twig\Environment->render()
#30 /home/vagrant/xx/vendor/craftcms/cms/src/web/View.php(481): craft\web\View->renderTemplate()
#31 /home/vagrant/xx/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate()
#32 /home/vagrant/xx/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format()
#33 /home/vagrant/xx/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#34 /home/vagrant/xx/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#35 /home/vagrant/xx/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#36 /home/vagrant/xx/web/index.php(12): yii\base\Application->run()
#37 {main}
```

</details>

**Next yii\di\NotInstantiableException: Failed to instantiate component or class "bymayo\porter\variables\PorterVariable". in /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php:509**

<details> 
  <summary>Stack trace 2:</summary>

```
#0 /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#1 /home/vagrant/xx/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#2 /home/vagrant/xx/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get()
#3 /home/vagrant/xx/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()
#4 /home/vagrant/xx/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\di\ServiceLocator->get()
#5 /home/vagrant/xx/vendor/craftcms/cms/src/helpers/Template.php(90): yii\di\ServiceLocator->__get()
#6 /home/vagrant/xx/storage/runtime/compiled_templates/e1/e1e944121636c2b1847dfdf004b49ece.php(41): craft\helpers\Template::attribute()
#7 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d3e78d63bf730e1f32521fa5c08aa48d->doDisplay()
#8 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#9 /home/vagrant/xx/storage/runtime/compiled_templates/08/082642088bfadabf7d3776435bb0e552.php(292): Twig\Template->display()
#10 /home/vagrant/xx/vendor/twig/twig/src/Template.php(171): __TwigTemplate_7129d93ddf3d1787758882ea8da39810->block_account()
#11 /home/vagrant/xx/storage/runtime/compiled_templates/b7/b7ce87a899d73972bedb70bcb29e1e8e.php(75): Twig\Template->displayBlock()
#12 /home/vagrant/xx/vendor/twig/twig/src/Template.php(171): __TwigTemplate_45fbd9b2468fd874474b0351c09ece51->block_content()
#13 /home/vagrant/xx/storage/runtime/compiled_templates/32/32a8ae1bc72d719289deb9e15af6ef11.php(166): Twig\Template->displayBlock()
#14 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_39c7f8fc1f11d4ab3a2f68b3e1f41840->doDisplay()
#15 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#16 /home/vagrant/xx/storage/runtime/compiled_templates/b7/b7ce87a899d73972bedb70bcb29e1e8e.php(49): Twig\Template->display()
#17 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_45fbd9b2468fd874474b0351c09ece51->doDisplay()
#18 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#19 /home/vagrant/xx/storage/runtime/compiled_templates/08/082642088bfadabf7d3776435bb0e552.php(49): Twig\Template->display()
#20 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7129d93ddf3d1787758882ea8da39810->doDisplay()
#21 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#22 /home/vagrant/xx/storage/runtime/compiled_templates/d1/d1ab8f71c923eafdf8501b95da04e4d3.php(55): Twig\Template->display()
#23 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4cf20a0adc7635f753889fec41c95f6e->doDisplay()
#24 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#25 /home/vagrant/xx/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#26 /home/vagrant/xx/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#27 /home/vagrant/xx/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#28 /home/vagrant/xx/vendor/craftcms/cms/src/web/View.php(428): Twig\Environment->render()
#29 /home/vagrant/xx/vendor/craftcms/cms/src/web/View.php(481): craft\web\View->renderTemplate()
#30 /home/vagrant/xx/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate()
#31 /home/vagrant/xx/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format()
#32 /home/vagrant/xx/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#33 /home/vagrant/xx/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#34 /home/vagrant/xx/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#35 /home/vagrant/xx/web/index.php(12): yii\base\Application->run()
#36 {main}
```

</details>

**Comment by bymayo** [comment]
@flo-bananzki Whoops! I went a bit crazy when tidying up the files it seems!

If you update to 1.0.1 and let me know if this fixes your issue.

**Comment by flo-bananzki** [comment]
Yeah, I thought that 😀
Works fine.
