### ISSUE TITLE
TypeError - array_merge(): Argument #2 must be of type array, null given

### ISSUE THREAD

**Issue by flo-bananzki** [bymayo/craft-porter#3]
When I try to load the DeleteAccountForm in my Template with this command: `{{ craft.porter.deleteAccountForm() }}` following Error occours:

**TypeError: array_merge(): Argument # 2 must be of type array, null given**

https://github.com/bymayo/craft-porter/blob/44ce2878f4f8d58c60a8c1d4bcd2dc92590bcdd0/src/services/DeleteAccount.php#L42

<details> 
  <summary>Stack trace:</summary>

```
#0 /home/vagrant/xx/vendor/bymayo/porter/src/services/DeleteAccount.php(42): array_merge()
#1 /home/vagrant/xx/vendor/bymayo/porter/src/variables/PorterVariable.php(20): bymayo\porter\services\DeleteAccount->renderFormTemplate()
#2 /home/vagrant/xx/vendor/twig/twig/src/Extension/CoreExtension.php(1607): bymayo\porter\variables\PorterVariable->deleteAccountForm()
#3 /home/vagrant/xx/vendor/craftcms/cms/src/helpers/Template.php(101): twig_get_attribute()
#4 /home/vagrant/xx/storage/runtime/compiled_templates/e1/e1e944121636c2b1847dfdf004b49ece.php(77): craft\helpers\Template::attribute()
#5 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d3e78d63bf730e1f32521fa5c08aa48d->doDisplay()
#6 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#7 /home/vagrant/xx/storage/runtime/compiled_templates/08/082642088bfadabf7d3776435bb0e552.php(290): Twig\Template->display()
#8 /home/vagrant/xx/vendor/twig/twig/src/Template.php(171): __TwigTemplate_7129d93ddf3d1787758882ea8da39810->block_account()
#9 /home/vagrant/xx/storage/runtime/compiled_templates/b7/b7ce87a899d73972bedb70bcb29e1e8e.php(75): Twig\Template->displayBlock()
#10 /home/vagrant/xx/vendor/twig/twig/src/Template.php(171): __TwigTemplate_45fbd9b2468fd874474b0351c09ece51->block_content()
#11 /home/vagrant/xx/storage/runtime/compiled_templates/32/32a8ae1bc72d719289deb9e15af6ef11.php(166): Twig\Template->displayBlock()
#12 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_39c7f8fc1f11d4ab3a2f68b3e1f41840->doDisplay()
#13 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#14 /home/vagrant/xx/storage/runtime/compiled_templates/b7/b7ce87a899d73972bedb70bcb29e1e8e.php(49): Twig\Template->display()
#15 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_45fbd9b2468fd874474b0351c09ece51->doDisplay()
#16 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#17 /home/vagrant/xx/storage/runtime/compiled_templates/08/082642088bfadabf7d3776435bb0e552.php(49): Twig\Template->display()
#18 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7129d93ddf3d1787758882ea8da39810->doDisplay()
#19 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#20 /home/vagrant/xx/storage/runtime/compiled_templates/d1/d1ab8f71c923eafdf8501b95da04e4d3.php(55): Twig\Template->display()
#21 /home/vagrant/xx/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4cf20a0adc7635f753889fec41c95f6e->doDisplay()
#22 /home/vagrant/xx/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#23 /home/vagrant/xx/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#24 /home/vagrant/xx/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#25 /home/vagrant/xx/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#26 /home/vagrant/xx/vendor/craftcms/cms/src/web/View.php(428): Twig\Environment->render()
#27 /home/vagrant/xx/vendor/craftcms/cms/src/web/View.php(481): craft\web\View->renderTemplate()
#28 /home/vagrant/xx/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate()
#29 /home/vagrant/xx/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format()
#30 /home/vagrant/xx/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#31 /home/vagrant/xx/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#32 /home/vagrant/xx/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#33 /home/vagrant/xx/web/index.php(12): yii\base\Application->run()
#34 {main}
```

</details>

When I load it with properties like this, everything now works just fine:

```
{{ craft.porter.deleteAccountForm(
   {
	  fieldClass: 'w-full',
	  fieldContainerClass: 'mb-6',
	  buttonClass: 'button',
	  buttonText: 'Profil endgültig löschen'
   }
) }}
```
So I think you can't merge the default properties array with custom properties if there are zero given. Probably check beforehand.

**Comment by bymayo** [comment]
@flo-bananzki Thanks for reporting this, it seems I only tested this with properties inside the variable. I've not added this test so it will do it without properties now.

But, I've fixed this. I also fixed the same issue on Magic Link and Deactivate Account forms.

If you update to 1.0.1 and let me know if this fixes your issue.

**Comment by flo-bananzki** [comment]
Thanks! The check does the Trick now. No errors anymore. 👌
